version: "2"
services:
  express-server:
    container_name: express-server
    restart: always
    build: .
    depends_on:
      - mongo-server
      - redis-server
    ports:
      - "8081:8081"
  mongo-server:
    container_name: mongo-server
    image: mongo
    ports:
      - "27017:27017"
  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"